language: node_js
node_js:
- 4.3.1
- stable
deploy:
  provider: npm
  email: npm@lossless.digital
  api_key:
    secure: k075QdAcmEdmAoVaP5vclLnZmhbZB39v85VIUMWAKXbIAU+liHrYZRlIEYfAaIUrf6sha+zAo/U/vjAN7c5ArB7J/HjCLJ3lsi2fWtaSRlYQrYX9/EhU0S+YZjRE8Jrn4hGTcce6I2mANBnEzvzlXrlKaqVvSqOqTO9nJ5aDBCGa5XT3EwlHKkRlAlL3ZOLrRg38R343E8ifZBsbn9G0e+RgDt0sic3WD8NME9lpsQ/99UZKH00duHbhF9nme5Sjdh86y01hvsaBf+CLR4gfS2IntnrCSrZbETFrsOBUyMnJZDQ3qlrjcEaiTkpJ4iSIqr+ftwGMMD6S1MxCTPqkp64UIeMz2Tg41HqoaeIg7z8cF0APv6M9ZAdWhsU43GqsMe70dK900JZpQAkQxMf/6NpPpGfZug6TwqLYSIRzvjvNrhYfuyoGfXdAxrM3SJMkIq6rwE+T/y36kZaC3CrQRyNZypNz0vW1M9HLjJUi2vO0U/CDn8tvi1p6ChrDXDfV3H2UIAMHFlAF+GrT7dMWwD+p+d8mc9gpAFEF9zMqAIJamPhwboJxoHjKQrqrq5czNm75ETL77AzfnU6CfQlG5dTIFnGId8y0ZxXvtpBruDoyC1+ZF23MYZmb+ipxQZM2oLCjNLeL3aEePc/JlSm6Gn8w3sIkZTG261F0XZxdApw=
  on:
    tags: true
    repo: pushrocks/npmts
env:
  global:
    secure: Xu27mG/9ScM/k4lKI5yyS4jSUh756lVJ+mP4UKe0FJI2jpVkOR8lZlLg8jqTRyhaXpRDnRo2O/yjA7P8/tC8tLe/GvoN4ooHU92axjUvuH+gxSvsI2Wodju+KrPHYrPPuDrPCf9M7mH0QQtUuPmcgcpPBuPQaNkTmLx/yfAaJYderLrPPoMU17BTG1C/7Glm7rIxj19SGCMjEK5ZMveCyNSTjqupS3kNw3mJU76W4SiEGY5NZWJKksEYS4nGP1cCnyci2fvwUSjmXtHqKXpXOJT6VZzqOX84zLIfdaqr47sQSXL11hWOofHyKA65ijQi83GLIGcxsLSKaNZU6UTj9+5TmEkgXh9yfmsXjEBhMc4FqmkG6HRsiW+OXchmarU024kXXo7TH6EPhVvKPclUovG5sidBF4M5EsdqdhJfY7VIj9cSXE8a/TqmL3LT+b86Z1vYwVXKXpO6aLQH+VnwtP3yKfa0Wp6qqUd0g+wAo/AvDIbfYMYxlwXA+B2K6AWjqVSWNj9qA4/j+avsmalI2KRWNeo8Mm67V2H1nBN2t/gj0I0AinsZG5ASQrKI2O+4HOzXzkMtzk8XTo9tZSaGaKsjVXktjicBgQztl1bJktQOeDdWt76XaIK+B+i3iiuIehXtxOP9k7yCu2PM0g/dUfqQn2gifqclaGCTxCngs3E=
